"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.supabase = void 0;
// This file is automatically generated. Do not edit it directly.
var supabase_js_1 = require("@supabase/supabase-js");
var SUPABASE_URL = "https://dtogvbjxbelmkrbvtxjy.supabase.co";
var SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0b2d2Ymp4YmVsbWtyYnZ0eGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzM2NzAsImV4cCI6MjA2MjAwOTY3MH0.V2IoGSDMZvDeUJ66HY5OXUBh2TlR2kzS4DOzCeTY3Fc";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
exports.supabase = (0, supabase_js_1.createClient)(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
